version: '3.7'

services:
  nginx:
    image: trackleap_platform_nginx
    build:
      context: .
      dockerfile: nginx/docker/Dockerfile
    command:  ["/bin/sh", "-c", "/usr/share/nginx/dockerize.sh"]
    depends_on:
      - app
    ports:
      - 80:80
    volumes:
      - ./application/public:/usr/share/nginx/html
      - ./application/storage/app/public/img:/usr/share/nginx/html/img

  app:
    image: trackleap_platform_app
    build:
      context: ./application
      dockerfile: docker/Dockerfile
    command:  "app"
    depends_on:
      - db
      - redis
    volumes:
      - ./application:/app
    environment:
      PHP_IDE_CONFIG: "serverName=two"

  worker:
    image: trackleap_platform_app
    build:
      context: ./application
      dockerfile: docker/Dockerfile
    command:  "worker"
    depends_on:
      - db
      - redis
    volumes:
      - ./application:/app
    environment:
      PHP_IDE_CONFIG: "serverName=two"

  cron:
    image: trackleap_platform_app
    build:
      context: ./application
      dockerfile: docker/Dockerfile
    command:  "cron"
    depends_on:
      - db
      - redis
    volumes:
      - ./application:/app
    environment:
      PHP_IDE_CONFIG: "serverName=two"

  db:
    image: postgres:12.1-alpine
    ports:
      - 5433:5433
    env_file:
      - .postgr-env
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:4-alpine
    volumes:
      - redisdata:/data
    ports:
      - 6378:6378

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    env_file:
      - elasticsearch.env
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

volumes:
  pgdata:
  redisdata:
  esdata:
